import type { AppCopy, LocaleMode } from "./types";

export const COPY: Record<LocaleMode, AppCopy> = {
  tr: {
    views: [
      { key: "overview", label: "Genel" },
      { key: "setup", label: "Kurulum" },
      { key: "live", label: "Canlı" },
      { key: "status", label: "Durum" },
      { key: "notes", label: "Notlar" },
    ],
    heroTitle: "Mobil Kamera İzleme",
    heroSubtitle:
      "Kamera kataloğu, canlı görüntü ve signaling bağlantısı fiziksel Android cihazda hazır.",
    badges: {
      device: { label: "Cihaz", value: "Android cihaz hazır" },
      camera: { label: "Kamera", value: "Canli akis hazir" },
      network: { label: "Ag", value: "go2rtc bagli" },
    },
    displayModeLabel: "Görünüm modu",
    modeLabels: { system: "Sistem", light: "Açık", dark: "Koyu" },
    languageLabel: "Dil",
    languageButtons: [
      { key: "tr", label: "TR" },
      { key: "en", label: "EN" },
      { key: "ru", label: "Русский" },
      { key: "ar", label: "العربية" },
    ],
    profileMenu: { about: "Hakkında", settings: "Ayarlar", profile: "Profil" },
    overview: {
      title: "Proje Durumu",
      subtitle:
        "Aktif kameraları seçip doğrudan canlı izlemeye geçebilirsin.",
      ready: { title: "Hazır parçalar", value: "Katalog, signaling, canlı görüntü" },
      pending: { title: "Bekleyen parçalar", value: "Uzak erişim, kullanıcı yetkileri" },
      final: { title: "Hedef", value: "WebRTC canlı görüntü + uzaktan erişim" },
      roadmap: [
        "IP'ler hazır olunca kamera envanteri eklenecek.",
        "RTSP kaynağı go2rtc veya benzeri bir medya köprüsüne bağlanacak.",
        "Gerçek WebRTC akışı canlı izleme alanında gösterilecek.",
        "Dış ağ ve mobil veri testleri için STUN/TURN açılacak.",
        "Panel; kamera, canlı görüntü ve ayar sayfalarına ayrılacak.",
      ],
      cameraListTitle: "Kameralar",
      cameraListSubtitle: "Signaling sunucusundan gelen aktif kamera kataloğu.",
      cameraSelectedLabel: "Seçili",
      cameraLiveButton: "Canlı izle",
      cameraLoadingLabel: "Yükleniyor",
      cameraErrorLabel: "Yerel veri",
      cameraEmptyLabel: "Kamera bulunamadı.",
    },
    setup: {
      title: "Kurulum Kontrol Listesi",
      subtitle: "Kamera verileri gelmeden önce yapılabilecek şeyler.",
      checklist: [
        {
          title: "Kamera bilgileri daha sonra bağlanacak",
          detail: "Kamera IP'si, RTSP adresi ve kanal verileri gelene kadar kabuk hazır tutulur.",
        },
        {
          title: "Signaling yapısı hazırlanır",
          detail: "WebRTC offer, answer ve ICE alışverişi için mesaj katmanı ayrılır.",
        },
        {
          title: "WebRTC oynatıcı alanı ayrılır",
          detail: "Canlı video paneli, kamera bağlantısı hazır olduğunda buraya yerleşir.",
        },
        {
          title: "STUN/TURN yapılandırması ayrılır",
          detail: "Doğrudan bağlantının yetmediği ağlar için yedek yol eklenir.",
        },
        {
          title: "Güvenlik katmanı planlanır",
          detail: "Kimlik doğrulama, token akışı, HTTPS ve WSS sonradan eklenebilir.",
        },
      ],
    },
    links: {
      title: "Entegrasyon Alanları",
      subtitle: "Kamera, RTSP, signaling ve relay ayarları için ayrılmış alanlar.",
      placeholders: [
        { label: "Kamera seçimi", hint: "Cihazlar bulununca doldurulacak." },
        { label: "RTSP kaynağı", hint: "Adres kamera veya NVR'dan gelecek." },
        { label: "Signaling uç noktası", hint: "WebRTC offer/answer için kullanılır." },
        { label: "TURN aktarımı", hint: "Sıkı NAT ve firewall durumları için yedek yol." },
        { label: "Kimlik doğrulama", hint: "Kullanıcı ve token akışı sonradan bağlanacak." },
      ],
    },
    settings: {
      title: "Ayarlar",
      subtitle: "Görünüm ve dil ayarları buradan değiştirilir.",
      appearanceTitle: "Görünüm",
      appearanceSubtitle: "Açık, koyu veya sistem temasını seç.",
      languageTitle: "Dil",
      languageSubtitle: "Türkçe, English, Русский veya العربية seç.",
      helperText: "Şimdilik sadece bu iki ayar aktif.",
    },
    live: {
      title: "Canlı Önizleme",
      subtitle: "Bu ekran go2rtc player üzerinden canlı kamera akışını gösterir.",
      sourceLabel: "Kaynak",
      sourceHint: "Kamera RTSP -> go2rtc -> WebRTC",
      connectButton: "Bağlan",
      disconnectButton: "Kes",
      stateIdle: "Boşta",
      stateConnecting: "Bağlanıyor",
      stateConnected: "Canlı",
      stateClosing: "Kapanıyor",
      stateDisconnected: "Ayrıldı",
      stateError: "Hata",
      streamHint: "Akış hazır olduğunda görüntü burada görünür.",
      emptyFrame: "Video bekleniyor",
      loadingLabel: "Canli goruntu yukleniyor",
      reloadButton: "Yeniden dene",
      fullscreenButton: "Tam ekran",
      closeFullscreenButton: "Kapat",
      loadErrorTitle: "Goruntu yuklenemedi",
      loadErrorHint: "go2rtc calisiyor mu ve telefon/emulator ayni gelistirme makinesine erisebiliyor mu kontrol et.",
      offlineTitle: "Gateway baglantisi kesildi",
      offlineHint: "Akilli diyafondaki go2rtc servisi durmus olabilir. Servisi yeniden baslatip tekrar dene.",
      lastMessageLabel: "Son mesaj",
      lastMessageEmpty: "Henüz sinyal yok. Bağlan ile WebRTC offer başlar.",
    },
    status: {
      title: "Sistem Durumu",
      subtitle:
        "Hazır olan, bekleyen ve veri isteyen parçalar birbirinden net biçimde ayrılır.",
      rows: [
        { name: "UI iskeleti", value: "Hazır", tone: "success" },
        { name: "Kamera baglantisi", value: "Hazir", tone: "success" },
        { name: "RTSP kaynagi", value: "Hazir", tone: "success" },
        { name: "Signaling server", value: "Hazir", tone: "success" },
        { name: "Mobil canli onizleme", value: "Hazir", tone: "success" },
        { name: "TURN / STUN", value: "Hazir", tone: "success" },
        { name: "Uzaktan erişim", value: "Test edildi", tone: "success" },
      ],
      signaling: {
        title: "Canlı Bağlantı",
        subtitle: "Mobil uygulamanın signaling server ile ilk gerçek bağlantı katmanı.",
        serverLabel: "Sunucu",
        roomLabel: "Oda",
        roleLabel: "Rol",
        clientLabel: "Client ID",
        membersLabel: "Üye sayısı",
        errorLabel: "Bağlantı hatası",
        lastMessageLabel: "Son mesaj",
        lastMessageEmpty: "Henüz mesaj yok. Bağlan düğmesine basınca join gönderilecek.",
        connectButton: "Bağlan",
        disconnectButton: "Kes",
        stateIdle: "Boşta",
        stateConnecting: "Bağlanıyor",
        stateConnected: "Bağlı",
        stateClosing: "Kapanıyor",
        stateDisconnected: "Ayrıldı",
        stateError: "Hata",
      },
    },
    notes: {
      title: "Notlar",
      subtitle: (activeView) => `Aktif bölüm şu anda ${activeView}.`,
      paragraph:
        "Bu uygulama özellikle önce ürün kabuğu olarak tasarlandı. Kamera verileri geldiğinde aynı yapı; kamera kartlarını, canlı önizlemeyi, bağlantı aksiyonlarını ve ayarları yeniden tasarım yapmadan kabul eder.",
      futureTitle: "Daha sonra doldurulacak alanlar",
      futureItems: [
        "Kamera listesi",
        "RTSP adresi",
        "Signaling uç noktası",
        "TURN aktarımı",
        "Giriş ve yetkiler",
      ],
    },
    waitingLabel: "Bekleniyor",
  },
  en: {
    views: [
      { key: "overview", label: "Overview" },
      { key: "setup", label: "Setup" },
      { key: "live", label: "Live" },
      { key: "status", label: "Status" },
      { key: "notes", label: "Notes" },
    ],
    heroTitle: "Mobile Camera View",
    heroSubtitle:
      "The camera catalog, live video, and signaling connection are ready on a physical Android device.",
    badges: {
      device: { label: "Device", value: "Android device ready" },
      camera: { label: "Camera", value: "Live stream ready" },
      network: { label: "Network", value: "go2rtc connected" },
    },
    displayModeLabel: "Display mode",
    modeLabels: { system: "System", light: "Light", dark: "Dark" },
    languageLabel: "Language",
    languageButtons: [
      { key: "tr", label: "TR" },
      { key: "en", label: "EN" },
      { key: "ru", label: "Русский" },
      { key: "ar", label: "العربية" },
    ],
    profileMenu: { about: "About", settings: "Settings", profile: "Profile" },
    overview: {
      title: "Project State",
      subtitle:
        "Select an active camera and open its live view directly.",
      ready: { title: "Ready parts", value: "Catalog, signaling, live video" },
      pending: { title: "Pending parts", value: "Remote access, user permissions" },
      final: { title: "Final target", value: "WebRTC live view + remote access" },
      roadmap: [
        "Add the camera inventory when the IPs are available.",
        "Connect the RTSP source to go2rtc or a similar media gateway.",
        "Render the real WebRTC stream in the live view panel.",
        "Enable STUN/TURN for off-network and mobile-data tests.",
        "Split the dashboard into dedicated camera, live view, and settings pages.",
      ],
      cameraListTitle: "Cameras",
      cameraListSubtitle: "Active camera catalog provided by the signaling server.",
      cameraSelectedLabel: "Selected",
      cameraLiveButton: "Watch live",
      cameraLoadingLabel: "Loading",
      cameraErrorLabel: "Local data",
      cameraEmptyLabel: "No cameras found.",
    },
    setup: {
      title: "Setup Checklist",
      subtitle: "What can be built now, before the actual camera data is shared.",
      checklist: [
        {
          title: "Camera information will be attached later",
          detail:
            "Keep the app shell ready until the camera IP, RTSP URL, and channel data arrive.",
        },
        {
          title: "Prepare the signaling structure",
          detail:
            "Separate the messaging layer for WebRTC offer, answer, and ICE exchange.",
        },
        {
          title: "Leave a slot for the WebRTC player",
          detail:
            "The final video panel will be mounted here after the camera connection is ready.",
        },
        {
          title: "Reserve STUN/TURN configuration",
          detail:
            "Add the fallback path for networks where direct connectivity is not enough.",
        },
        {
          title: "Plan the security layer",
          detail:
            "Authentication, token flow, HTTPS, and WSS can be connected later without redesign.",
        },
      ],
    },
    links: {
      title: "Integration Slots",
      subtitle: "Reserved areas for camera, RTSP, signaling, and relay settings.",
      placeholders: [
        { label: "Camera selection", hint: "Will be filled once devices are discovered." },
        { label: "RTSP source", hint: "The address will arrive from the camera or NVR." },
        { label: "Signaling endpoint", hint: "Used for WebRTC offer/answer exchange." },
        { label: "TURN relay", hint: "Fallback route for strict NAT and firewall cases." },
        { label: "Authentication", hint: "User and token flow will be attached later." },
      ],
    },
    settings: {
      title: "Settings",
      subtitle: "Change appearance and language from here.",
      appearanceTitle: "Appearance",
      appearanceSubtitle: "Choose light, dark, or system theme.",
      languageTitle: "Language",
      languageSubtitle: "Choose Türkçe, English, Русский, or العربية.",
      helperText: "Only these two settings are active for now.",
    },
    live: {
      title: "Live Preview",
      subtitle: "This screen shows the live camera stream through the go2rtc player.",
      sourceLabel: "Source",
      sourceHint: "Camera RTSP -> go2rtc -> WebRTC",
      connectButton: "Connect",
      disconnectButton: "Disconnect",
      stateIdle: "Idle",
      stateConnecting: "Connecting",
      stateConnected: "Live",
      stateClosing: "Closing",
      stateDisconnected: "Disconnected",
      stateError: "Error",
      streamHint: "When the stream is ready, the video will appear here.",
      emptyFrame: "Waiting for video",
      loadingLabel: "Loading live view",
      reloadButton: "Retry",
      fullscreenButton: "Full screen",
      closeFullscreenButton: "Close",
      loadErrorTitle: "Video could not load",
      loadErrorHint: "Check that go2rtc is running and the phone/emulator can reach the development machine.",
      offlineTitle: "Gateway connection lost",
      offlineHint: "The go2rtc service on the smart intercom may be down. Start it again and retry.",
      lastMessageLabel: "Last message",
      lastMessageEmpty: "No signaling yet. Connect starts the WebRTC offer.",
    },
    status: {
      title: "System Status",
      subtitle:
        "Clear separation between what is ready, what is pending, and what still needs data.",
      rows: [
        { name: "UI shell", value: "Ready", tone: "success" },
        { name: "Camera connection", value: "Ready", tone: "success" },
        { name: "RTSP source", value: "Ready", tone: "success" },
        { name: "Signaling server", value: "Ready", tone: "success" },
        { name: "Mobile live preview", value: "Ready", tone: "success" },
        { name: "TURN / STUN", value: "Ready", tone: "success" },
        { name: "Remote access", value: "Tested", tone: "success" },
      ],
      signaling: {
        title: "Live Connection",
        subtitle: "The first real signaling layer between the mobile app and the server.",
        serverLabel: "Server",
        roomLabel: "Room",
        roleLabel: "Role",
        clientLabel: "Client ID",
        membersLabel: "Members",
        errorLabel: "Connection error",
        lastMessageLabel: "Last message",
        lastMessageEmpty: "No messages yet. Press Connect to send a join message.",
        connectButton: "Connect",
        disconnectButton: "Disconnect",
        stateIdle: "Idle",
        stateConnecting: "Connecting",
        stateConnected: "Connected",
        stateClosing: "Closing",
        stateDisconnected: "Disconnected",
        stateError: "Error",
      },
    },
    notes: {
      title: "Notes",
      subtitle: (activeView) => `The active section is currently ${activeView}.`,
      paragraph:
        "The app is intentionally designed as a product shell first. Once the camera data arrives, this same structure will accept camera cards, live preview, connection actions, and settings without a redesign.",
      futureTitle: "What will be filled later",
      futureItems: [
        "Camera list",
        "RTSP address",
        "Signaling endpoint",
        "TURN relay",
        "Login and permissions",
      ],
    },
    waitingLabel: "Waiting",
  },
  ar: {
    views: [
      { key: "overview", label: "نظرة عامة" },
      { key: "setup", label: "الإعداد" },
      { key: "live", label: "مباشر" },
      { key: "status", label: "الحالة" },
      { key: "notes", label: "ملاحظات" },
    ],
    heroTitle: "عرض الكاميرا عبر الهاتف",
    heroSubtitle:
      "قائمة الكاميرات والفيديو المباشر واتصال signaling جاهزة على جهاز Android فعلي.",
    badges: {
      device: { label: "الجهاز", value: "جهاز Android جاهز" },
      camera: { label: "الكاميرا", value: "البث المباشر جاهز" },
      network: { label: "الشبكة", value: "go2rtc متصل" },
    },
    displayModeLabel: "وضع العرض",
    modeLabels: { system: "النظام", light: "فاتح", dark: "داكن" },
    languageLabel: "اللغة",
    languageButtons: [
      { key: "tr", label: "TR" },
      { key: "en", label: "EN" },
      { key: "ru", label: "Русский" },
      { key: "ar", label: "العربية" },
    ],
    profileMenu: { about: "حول", settings: "الإعدادات", profile: "الملف الشخصي" },
    overview: {
      title: "حالة المشروع",
      subtitle:
        "اختر كاميرا نشطة وانتقل مباشرة إلى العرض المباشر.",
      ready: { title: "الأجزاء الجاهزة", value: "القائمة، signaling، الفيديو المباشر" },
      pending: { title: "الأجزاء المعلقة", value: "الوصول البعيد وصلاحيات المستخدم" },
      final: { title: "الهدف النهائي", value: "عرض مباشر عبر WebRTC + وصول عن بعد" },
      roadmap: [
        "إضافة قائمة الكاميرات عندما تصبح عناوين IP متاحة.",
        "ربط مصدر RTSP بـ go2rtc أو بوابة وسائط مشابهة.",
        "عرض بث WebRTC الحقيقي داخل شاشة المشاهدة.",
        "تفعيل STUN/TURN للاختبارات خارج الشبكة وبيانات الهاتف.",
        "تقسيم اللوحة إلى صفحات للكاميرا والعرض المباشر والإعدادات.",
      ],
      cameraListTitle: "الكاميرات",
      cameraListSubtitle: "قائمة الكاميرات النشطة من خادم signaling.",
      cameraSelectedLabel: "محددة",
      cameraLiveButton: "مشاهدة مباشرة",
      cameraLoadingLabel: "جارٍ التحميل",
      cameraErrorLabel: "بيانات محلية",
      cameraEmptyLabel: "لم يتم العثور على كاميرات.",
    },
    setup: {
      title: "قائمة الإعداد",
      subtitle: "ما يمكن بناؤه الآن قبل وصول بيانات الكاميرا الفعلية.",
      checklist: [
        {
          title: "ستُضاف معلومات الكاميرا لاحقًا",
          detail:
            "يظل هيكل التطبيق جاهزًا حتى وصول IP الكاميرا وعنوان RTSP وبيانات القناة.",
        },
        {
          title: "تحضير بنية signaling",
          detail: "فصل طبقة الرسائل الخاصة بـ WebRTC: offer وanswer وتبادل ICE.",
        },
        {
          title: "تخصيص مساحة لمشغل WebRTC",
          detail: "ستتم إضافة لوحة الفيديو هنا بعد جاهزية اتصال الكاميرا.",
        },
        {
          title: "حجز إعدادات STUN/TURN",
          detail: "إضافة مسار بديل للشبكات التي لا تكفي فيها الاتصالات المباشرة.",
        },
        {
          title: "تخطيط طبقة الأمان",
          detail: "المصادقة والتوكن وHTTPS وWSS يمكن ربطها لاحقًا دون إعادة تصميم.",
        },
      ],
    },
    links: {
      title: "مساحات التكامل",
      subtitle: "أماكن مخصصة لإعدادات الكاميرا وRTSP وsignaling والوسيط.",
      placeholders: [
        { label: "اختيار الكاميرا", hint: "سيُملأ عند اكتشاف الأجهزة." },
        { label: "مصدر RTSP", hint: "سيأتي العنوان من الكاميرا أو NVR." },
        { label: "نقطة signaling", hint: "تُستخدم لتبادل offer/answer في WebRTC." },
        { label: "TURN relay", hint: "مسار احتياطي لحالات NAT وfirewall الصارمة." },
        { label: "المصادقة", hint: "سيتم ربط المستخدم والتوكن لاحقًا." },
      ],
    },
    settings: {
      title: "الإعدادات",
      subtitle: "يمكنك تغيير المظهر واللغة من هنا.",
      appearanceTitle: "المظهر",
      appearanceSubtitle: "اختر الوضع الفاتح أو الداكن أو النظام.",
      languageTitle: "اللغة",
      languageSubtitle: "اختر Türkçe أو English أو Русский أو العربية.",
      helperText: "حالياً هذان الإعدادان فقط نشطان.",
    },
    live: {
      title: "معاينة مباشرة",
      subtitle: "تُظهر هذه الشاشة بث الكاميرا المباشر عبر مشغل go2rtc.",
      sourceLabel: "المصدر",
      sourceHint: "الكاميرا RTSP -> go2rtc -> WebRTC",
      connectButton: "اتصال",
      disconnectButton: "فصل",
      stateIdle: "خامل",
      stateConnecting: "جارٍ الاتصال",
      stateConnected: "مباشر",
      stateClosing: "جارٍ الإغلاق",
      stateDisconnected: "منفصل",
      stateError: "خطأ",
      streamHint: "عند جاهزية البث ستظهر الصورة هنا.",
      emptyFrame: "بانتظار الفيديو",
      loadingLabel: "جارٍ تحميل البث المباشر",
      reloadButton: "إعادة المحاولة",
      fullscreenButton: "ملء الشاشة",
      closeFullscreenButton: "إغلاق",
      loadErrorTitle: "تعذر تحميل الفيديو",
      loadErrorHint: "تحقق من أن go2rtc يعمل وأن الهاتف أو المحاكي يستطيع الوصول إلى جهاز التطوير.",
      offlineTitle: "انقطع اتصال البوابة",
      offlineHint: "قد تكون خدمة go2rtc على جهاز الإنتركم الذكي قد توقفت. أعد تشغيلها ثم حاول مرة أخرى.",
      lastMessageLabel: "آخر رسالة",
      lastMessageEmpty: "لا يوجد signaling بعد. زر الاتصال يبدأ WebRTC offer.",
    },
    status: {
      title: "حالة النظام",
      subtitle:
        "فصل واضح بين ما هو جاهز وما هو معلّق وما يحتاج إلى بيانات إضافية.",
      rows: [
        { name: "هيكل UI", value: "جاهز", tone: "success" },
        { name: "اتصال الكاميرا", value: "جاهز", tone: "success" },
        { name: "مصدر RTSP", value: "جاهز", tone: "success" },
        { name: "خادم signaling", value: "جاهز", tone: "success" },
        { name: "المعاينة المباشرة في التطبيق", value: "جاهزة", tone: "success" },
        { name: "TURN / STUN", value: "جاهز", tone: "success" },
        { name: "الوصول البعيد", value: "تم اختباره", tone: "success" },
      ],
      signaling: {
        title: "الاتصال المباشر",
        subtitle: "أول طبقة signaling حقيقية بين التطبيق والخادم.",
        serverLabel: "الخادم",
        roomLabel: "الغرفة",
        roleLabel: "الدور",
        clientLabel: "Client ID",
        membersLabel: "عدد الأعضاء",
        errorLabel: "خطأ في الاتصال",
        lastMessageLabel: "آخر رسالة",
        lastMessageEmpty: "لا توجد رسائل بعد. اضغط اتصال لإرسال join.",
        connectButton: "اتصال",
        disconnectButton: "فصل",
        stateIdle: "خامل",
        stateConnecting: "جارٍ الاتصال",
        stateConnected: "متصل",
        stateClosing: "جارٍ الإغلاق",
        stateDisconnected: "منفصل",
        stateError: "خطأ",
      },
    },
    notes: {
      title: "ملاحظات",
      subtitle: (activeView) => `القسم النشط حاليًا هو ${activeView}.`,
      paragraph:
        "تم تصميم التطبيق عمدًا كهيكل منتج أولًا. عند وصول بيانات الكاميرا، ستستوعب هذه البنية بطاقات الكاميرا والمعاينة المباشرة وإجراءات الاتصال والإعدادات دون إعادة تصميم.",
      futureTitle: "ما سيتم تعبئته لاحقًا",
      futureItems: [
        "قائمة الكاميرات",
        "عنوان RTSP",
        "نقطة signaling",
        "TURN relay",
        "تسجيل الدخول والصلاحيات",
      ],
    },
    waitingLabel: "بانتظار",
  },
  ru: {
    views: [
      { key: "overview", label: "Обзор" },
      { key: "setup", label: "Установка" },
      { key: "live", label: "Эфир" },
      { key: "status", label: "Статус" },
      { key: "notes", label: "Заметки" },
    ],
    heroTitle: "Мобильный просмотр камеры",
    heroSubtitle:
      "Каталог камер, прямое видео и signaling-соединение готовы на физическом Android-устройстве.",
    badges: {
      device: { label: "Устройство", value: "Android-устройство готово" },
      camera: { label: "Камера", value: "Прямой поток готов" },
      network: { label: "Сеть", value: "go2rtc подключен" },
    },
    displayModeLabel: "Режим отображения",
    modeLabels: { system: "Система", light: "Светлая", dark: "Темная" },
    languageLabel: "Язык",
    languageButtons: [
      { key: "tr", label: "TR" },
      { key: "en", label: "EN" },
      { key: "ru", label: "Русский" },
      { key: "ar", label: "العربية" },
    ],
    profileMenu: { about: "О приложении", settings: "Настройки", profile: "Профиль" },
    overview: {
      title: "Состояние проекта",
      subtitle: "Выберите активную камеру и сразу откройте прямой эфир.",
      ready: { title: "Готово", value: "Каталог, signaling, прямое видео" },
      pending: { title: "Ожидает", value: "Удаленный доступ и права пользователей" },
      final: { title: "Цель", value: "WebRTC видео + удаленный доступ" },
      roadmap: [
        "После получения IP будет добавлен список камер.",
        "RTSP-источник будет подключен к go2rtc или похожему медиашлюзу.",
        "Реальный поток WebRTC появится в блоке прямого эфира.",
        "Для внешней сети и мобильного интернета будет добавлен STUN/TURN.",
        "Панель разделится на отдельные экраны камеры, эфира и настроек.",
      ],
      cameraListTitle: "Камеры",
      cameraListSubtitle: "Активный каталог камер от signaling-сервера.",
      cameraSelectedLabel: "Выбрана",
      cameraLiveButton: "Смотреть эфир",
      cameraLoadingLabel: "Загрузка",
      cameraErrorLabel: "Локальные данные",
      cameraEmptyLabel: "Камеры не найдены.",
    },
    setup: {
      title: "Чеклист установки",
      subtitle: "Что можно подготовить до получения реальных данных камеры.",
      checklist: [
        {
          title: "Информация о камере будет добавлена позже",
          detail: "Каркас приложения остается готовым, пока не придут IP камеры, RTSP-адрес и данные канала.",
        },
        {
          title: "Подготовить signaling-слой",
          detail: "Выделяется слой сообщений для WebRTC offer, answer и обмена ICE.",
        },
        {
          title: "Оставить место под WebRTC-плеер",
          detail: "Финальная видеопанель будет размещена здесь после готовности подключения камеры.",
        },
        {
          title: "Зарезервировать STUN/TURN",
          detail: "Добавляется запасной путь для сетей, где прямого соединения недостаточно.",
        },
        {
          title: "Спланировать безопасность",
          detail: "Аутентификация, токены, HTTPS и WSS позже можно подключить без переделки интерфейса.",
        },
      ],
    },
    links: {
      title: "Точки интеграции",
      subtitle: "Зарезервированные области для камеры, RTSP, signaling и relay-настроек.",
      placeholders: [
        { label: "Выбор камеры", hint: "Заполнится после обнаружения устройств." },
        { label: "RTSP-источник", hint: "Адрес придет от камеры или NVR." },
        { label: "Signaling endpoint", hint: "Используется для обмена WebRTC offer/answer." },
        { label: "TURN relay", hint: "Запасной маршрут для строгого NAT и firewall." },
        { label: "Аутентификация", hint: "Пользователь и токены будут подключены позже." },
      ],
    },
    settings: {
      title: "Настройки",
      subtitle: "Здесь меняются внешний вид и язык.",
      appearanceTitle: "Оформление",
      appearanceSubtitle: "Выберите светлую, темную или системную тему.",
      languageTitle: "Язык",
      languageSubtitle: "Выберите Türkçe, English, Русский или العربية.",
      helperText: "Сейчас активны только эти две настройки.",
    },
    live: {
      title: "Прямой эфир",
      subtitle: "Этот экран показывает живой поток камеры через go2rtc player.",
      sourceLabel: "Источник",
      sourceHint: "Камера RTSP -> go2rtc -> WebRTC",
      connectButton: "Подключить",
      disconnectButton: "Отключить",
      stateIdle: "Ожидание",
      stateConnecting: "Подключение",
      stateConnected: "Эфир",
      stateClosing: "Закрытие",
      stateDisconnected: "Отключено",
      stateError: "Ошибка",
      streamHint: "Когда поток будет готов, видео появится здесь.",
      emptyFrame: "Ожидание видео",
      loadingLabel: "Загрузка прямого эфира",
      reloadButton: "Повторить",
      fullscreenButton: "На весь экран",
      closeFullscreenButton: "Закрыть",
      loadErrorTitle: "Не удалось загрузить видео",
      loadErrorHint: "Проверь, что go2rtc запущен и телефон или эмулятор видит машину разработки.",
      offlineTitle: "Соединение с gateway потеряно",
      offlineHint: "Сервис go2rtc на умном домофоне мог остановиться. Запусти его снова и повтори попытку.",
      lastMessageLabel: "Последнее сообщение",
      lastMessageEmpty: "Пока нет signaling. Кнопка подключения запускает WebRTC offer.",
    },
    status: {
      title: "Состояние системы",
      subtitle: "Четко разделено, что уже готово, что ожидает и что еще требует данных.",
      rows: [
        { name: "Каркас UI", value: "Готово", tone: "success" },
        { name: "Подключение камеры", value: "Готово", tone: "success" },
        { name: "RTSP-источник", value: "Готово", tone: "success" },
        { name: "Signaling server", value: "Готово", tone: "success" },
        { name: "Мобильный предпросмотр", value: "Готово", tone: "success" },
        { name: "TURN / STUN", value: "Готово", tone: "success" },
        { name: "Удаленный доступ", value: "Проверено", tone: "success" },
      ],
      signaling: {
        title: "Живое соединение",
        subtitle: "Первый реальный signaling-слой между мобильным приложением и сервером.",
        serverLabel: "Сервер",
        roomLabel: "Комната",
        roleLabel: "Роль",
        clientLabel: "Client ID",
        membersLabel: "Участники",
        errorLabel: "Ошибка соединения",
        lastMessageLabel: "Последнее сообщение",
        lastMessageEmpty: "Пока нет сообщений. Нажми Подключить, чтобы отправить join.",
        connectButton: "Подключить",
        disconnectButton: "Отключить",
        stateIdle: "Ожидание",
        stateConnecting: "Подключение",
        stateConnected: "Подключено",
        stateClosing: "Закрытие",
        stateDisconnected: "Отключено",
        stateError: "Ошибка",
      },
    },
    notes: {
      title: "Заметки",
      subtitle: (activeView) => `Сейчас открыт раздел ${activeView}.`,
      paragraph:
        "Приложение изначально собрано как продуктовый каркас. Когда придут данные камеры, эта же структура примет карточки камер, живой просмотр, действия подключения и настройки без переработки интерфейса.",
      futureTitle: "Будет добавлено позже",
      futureItems: [
        "Список камер",
        "RTSP-адрес",
        "Signaling endpoint",
        "TURN relay",
        "Вход и права доступа",
      ],
    },
    waitingLabel: "Ожидание",
  },
};
