import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    paddingHorizontal: 18,
    paddingBottom: 30,
  },
  hero: {
    marginBottom: 16,
  },
  heroTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  brandMark: {
    width: 58,
    height: 58,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 5,
  },
  brandLogoImage: {
    width: 42,
    height: 42,
  },
  heroCopy: {
    marginTop: 10,
  },
  profileButton: {
    width: 52,
    height: 52,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 2,
  },
  profileDock: {
    alignItems: "flex-end",
    position: "relative",
  },
  profileGlyph: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  profileHead: {
    width: 9,
    height: 9,
    borderRadius: 999,
    marginBottom: 2,
  },
  profileShoulders: {
    width: 18,
    height: 11,
    borderRadius: 999,
    borderWidth: 2,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  title: {
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "900",
    letterSpacing: 0,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 22,
  },
  heroMetaRow: {
    marginTop: 14,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  profileMenu: {
    zIndex: 30,
    elevation: 20,
    borderRadius: 22,
    borderWidth: 1,
    padding: 14,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.16,
    shadowRadius: 20,
  },
  profileMenuBar: {
    flexDirection: "row",
    gap: 10,
  },
  profileMenuItemButton: {
    flex: 1,
    minHeight: 54,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  profileMenuItemText: {
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0,
    textAlign: "center",
  },
  badge: {
    minWidth: 106,
    flexGrow: 1,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  badgeLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    marginBottom: 4,
    letterSpacing: 0,
  },
  badgeValue: {
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  tabBar: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 2,
  },
  tabButton: {
    flexGrow: 1,
    minWidth: 82,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  tabText: {
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0,
  },
  settingsGrid: {
    gap: 12,
  },
  settingsPanel: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
  },
  settingsPanelTitle: {
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 4,
  },
  settingsPanelHint: {
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  settingsChoiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  settingsChoiceButton: {
    minWidth: 100,
  },
  settingsChoiceButtonCompact: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 8,
  },
  settingsChoiceButtonTextCompact: {
    fontSize: 12,
  },
  settingsHelper: {
    marginTop: 10,
    fontSize: 13,
    lineHeight: 18,
  },
  livePanel: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    marginBottom: 14,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 2,
  },
  liveHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  livePanelTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "900",
    marginBottom: 4,
  },
  livePanelHint: {
    fontSize: 12,
    lineHeight: 18,
  },
  liveStatePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: "flex-start",
  },
  liveStateText: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
  },
  liveVideoFrame: {
    minHeight: 240,
    borderRadius: 18,
    borderWidth: 1,
    overflow: "hidden",
    marginBottom: 12,
    position: "relative",
  },
  liveVideo: {
    width: "100%",
    height: 260,
    backgroundColor: "#000000",
  },
  liveVideoOverlay: {
    ...StyleSheet.absoluteFill,
    minHeight: 240,
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    backgroundColor: "rgba(255,255,255,0.92)",
  },
  liveInlineFullscreenButton: {
    position: "absolute",
    top: 12,
    right: 12,
    minHeight: 40,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
  },
  liveInlineFullscreenText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
  },
  liveVideoPlaceholder: {
    minHeight: 240,
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
  },
  liveVideoPlaceholderText: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "900",
    marginBottom: 6,
    textAlign: "center",
  },
  liveVideoPlaceholderHint: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  liveReloadButton: {
    minHeight: 42,
    marginTop: 14,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  liveReloadButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0,
  },
  liveActionRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  liveActionButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  liveActionButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0,
  },
  liveFullscreenRoot: {
    flex: 1,
    backgroundColor: "#05070d",
  },
  liveFullscreenHeader: {
    paddingTop: 48,
    paddingHorizontal: 18,
    paddingBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  liveFullscreenTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
    letterSpacing: 0,
  },
  liveFullscreenSubtitle: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 18,
  },
  liveFullscreenCloseButton: {
    minHeight: 40,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  liveFullscreenCloseText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0,
  },
  liveFullscreenVideoWrap: {
    flex: 1,
    backgroundColor: "#000000",
  },
  liveFullscreenVideo: {
    flex: 1,
    backgroundColor: "#000000",
  },
  liveErrorBox: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
    marginBottom: 12,
  },
  liveErrorTitle: {
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 4,
  },
  liveErrorText: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  signalPanel: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    marginBottom: 14,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 2,
  },
  signalHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  signalPanelTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "900",
    marginBottom: 4,
  },
  signalPanelHint: {
    fontSize: 12,
    lineHeight: 18,
  },
  signalStatePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: "flex-start",
  },
  signalStateText: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
  },
  signalMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  signalMetaItem: {
    flexGrow: 1,
    minWidth: 136,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  signalMetaLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    marginBottom: 4,
    letterSpacing: 0,
  },
  signalMetaValue: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
  },
  signalErrorBox: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
    marginBottom: 12,
  },
  signalErrorTitle: {
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 4,
  },
  signalErrorText: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  signalButtonRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  signalButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  signalButtonText: {
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0,
  },
  signalLogBox: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
  },
  signalLogLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    marginBottom: 4,
    letterSpacing: 0,
  },
  signalLogText: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  sectionCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
    marginTop: 14,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 2,
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
    marginBottom: 6,
  },
  sectionSubtitle: {
    fontSize: 13,
    lineHeight: 20,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 14,
  },
  cameraCatalogHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 8,
  },
  cameraCatalogTitle: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "900",
  },
  cameraCatalogSubtitle: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 18,
  },
  cameraCatalogState: {
    minWidth: 34,
    textAlign: "center",
    fontSize: 12,
    lineHeight: 20,
    fontWeight: "900",
  },
  cameraCatalogList: {
    marginBottom: 10,
  },
  cameraCatalogRow: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
  },
  cameraSelectionDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  cameraSelectionDotInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  cameraCatalogName: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "900",
  },
  cameraCatalogMeta: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 18,
  },
  cameraSelectedText: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "900",
  },
  cameraCatalogEmpty: {
    paddingVertical: 16,
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
  cameraLiveButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    marginBottom: 16,
  },
  cameraLiveButtonText: {
    color: "#ffffff",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  metricCard: {
    flexGrow: 1,
    minWidth: 150,
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  metricAccent: {
    width: 38,
    height: 5,
    borderRadius: 999,
    marginBottom: 12,
  },
  metricLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    marginBottom: 6,
    letterSpacing: 0,
  },
  metricValue: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  roadmap: {
    borderRadius: 18,
    overflow: "hidden",
  },
  roadmapRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 14,
  },
  stepPill: {
    width: 32,
    height: 32,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  stepPillText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  roadmapText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 20,
    paddingTop: 4,
    fontWeight: "600",
  },
  checkRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 12,
  },
  checkIndex: {
    width: 32,
    height: 32,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  checkIndexText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  checkCopy: {
    flex: 1,
  },
  checkTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "800",
    marginBottom: 4,
  },
  checkDetail: {
    fontSize: 13,
    lineHeight: 20,
  },
  statusList: {
    gap: 2,
  },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  statusName: {
    fontSize: 13,
    fontWeight: "700",
  },
  statusValue: {
    fontSize: 13,
    fontWeight: "900",
  },
  longText: {
    fontSize: 13,
    lineHeight: 22,
  },
  noteBox: {
    marginTop: 14,
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  noteBoxTitle: {
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 8,
  },
  noteBoxText: {
    fontSize: 13,
    lineHeight: 20,
  },
  ltrText: {
    textAlign: "left",
  },
  rtlText: {
    textAlign: "right",
    writingDirection: "rtl",
  },
  textLTR: {
    textAlign: "left",
    writingDirection: "ltr",
  },
  textRTL: {
    textAlign: "right",
    writingDirection: "rtl",
  },
});
